server:
  port: 9001
  tomcat:
    uri-encoding: utf-8
  servlet:
    context-path: /fileserver
  max-http-header-size: 80KB
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 200MB
logging:
  level:
    com.followr.mapper: debug
fileserver:
  basepath: D:\\fileserverHome